/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*!
 * @brief
 * NMI Pin Enable: PTB4/KBI0_P12/FTM2_CH4/SPI0_MISO/ACMP1_IN2/NMI pin functions as PTB4, KBI0_P12, FTM2_CH4,
 * SPI0_MISO or ACMP1_IN2.
 */
#define SOPT0_NMIE_0b0 0x00u
/*!
 * @brief UART0 RxD Filter Select: RXD0 input signal is connected to UART0 module directly. */
#define SOPT0_RXDFE_0b00 0x00u

/*! @name PORTA6 (number 38), GATEOUT4
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_RELEASE_GATEOUT4_FGPIO FGPIOA             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_RELEASE_GATEOUT4_GPIO GPIOA               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_RELEASE_GATEOUT4_GPIO_PORT kGPIO_PORTA    /*!<@brief PORTA GPIO port: PORTA */
#define BOARD_INITPINS_RELEASE_GATEOUT4_GPIO_PIN_MASK (1U << 6U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_RELEASE_GATEOUT4_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_RELEASE_GATEOUT4_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_RELEASE_GATEOUT4_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                                 /* @} */

/*! @name PORTB2 (number 32), P_ASCK
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_RELEASE_P_ASCK_FGPIO FGPIOA             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_RELEASE_P_ASCK_GPIO GPIOA               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_RELEASE_P_ASCK_GPIO_PORT kGPIO_PORTB    /*!<@brief PORTA GPIO port: PORTA */
#define BOARD_INITPINS_RELEASE_P_ASCK_GPIO_PIN_MASK (1U << 10U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_RELEASE_P_ASCK_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_RELEASE_P_ASCK_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_RELEASE_P_ASCK_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORTB3 (number 31), P_ADAT
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_RELEASE_P_ADAT_FGPIO FGPIOA             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_RELEASE_P_ADAT_GPIO GPIOA               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_RELEASE_P_ADAT_GPIO_PORT kGPIO_PORTB    /*!<@brief PORTA GPIO port: PORTA */
#define BOARD_INITPINS_RELEASE_P_ADAT_GPIO_PIN_MASK (1U << 11U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_RELEASE_P_ADAT_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_RELEASE_P_ADAT_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_RELEASE_P_ADAT_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORTB5 (number 18), LED1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_RELEASE_LED1_FGPIO FGPIOA             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_RELEASE_LED1_GPIO GPIOA               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_RELEASE_LED1_GPIO_PORT kGPIO_PORTB    /*!<@brief PORTA GPIO port: PORTA */
#define BOARD_INITPINS_RELEASE_LED1_GPIO_PIN_MASK (1U << 13U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_RELEASE_LED1_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_RELEASE_LED1_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_RELEASE_LED1_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PORTC0 (number 26), P_ARCK
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_RELEASE_P_ARCK_FGPIO FGPIOA             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_RELEASE_P_ARCK_GPIO GPIOA               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_RELEASE_P_ARCK_GPIO_PORT kGPIO_PORTC    /*!<@brief PORTA GPIO port: PORTA */
#define BOARD_INITPINS_RELEASE_P_ARCK_GPIO_PIN_MASK (1U << 16U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_RELEASE_P_ARCK_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_RELEASE_P_ARCK_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_RELEASE_P_ARCK_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORTC1 (number 25), P_KDAT
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_RELEASE_P_KCLK_FGPIO FGPIOA             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_RELEASE_P_KCLK_GPIO GPIOA               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_RELEASE_P_KCLK_GPIO_PORT kGPIO_PORTC    /*!<@brief PORTA GPIO port: PORTA */
#define BOARD_INITPINS_RELEASE_P_KCLK_GPIO_PIN_MASK (1U << 17U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_RELEASE_P_KCLK_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_RELEASE_P_KCLK_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_RELEASE_P_KCLK_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORTC2 (number 21), LED3
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_RELEASE_LED3_FGPIO FGPIOA             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_RELEASE_LED3_GPIO GPIOA               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_RELEASE_LED3_GPIO_PORT kGPIO_PORTC    /*!<@brief PORTA GPIO port: PORTA */
#define BOARD_INITPINS_RELEASE_LED3_GPIO_PIN_MASK (1U << 18U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_RELEASE_LED3_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_RELEASE_LED3_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_RELEASE_LED3_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PORTC3 (number 20), LED2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_RELEASE_LED2_FGPIO FGPIOA             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_RELEASE_LED2_GPIO GPIOA               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_RELEASE_LED2_GPIO_PORT kGPIO_PORTC    /*!<@brief PORTA GPIO port: PORTA */
#define BOARD_INITPINS_RELEASE_LED2_GPIO_PIN_MASK (1U << 19U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_RELEASE_LED2_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_RELEASE_LED2_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_RELEASE_LED2_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PORTC5 (number 61), SYNCOUT
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_RELEASE_SYNCOUT_FGPIO FGPIOA             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_RELEASE_SYNCOUT_GPIO GPIOA               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_RELEASE_SYNCOUT_GPIO_PORT kGPIO_PORTC    /*!<@brief PORTA GPIO port: PORTA */
#define BOARD_INITPINS_RELEASE_SYNCOUT_GPIO_PIN_MASK (1U << 21U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_RELEASE_SYNCOUT_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_RELEASE_SYNCOUT_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_RELEASE_SYNCOUT_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                                /* @} */

/*! @name PORTC6 (number 52), KEYSCAN1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_RELEASE_KEYSCAN1_FGPIO FGPIOA             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_RELEASE_KEYSCAN1_GPIO GPIOA               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_RELEASE_KEYSCAN1_GPIO_PORT kGPIO_PORTC    /*!<@brief PORTA GPIO port: PORTA */
#define BOARD_INITPINS_RELEASE_KEYSCAN1_GPIO_PIN_MASK (1U << 22U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_RELEASE_KEYSCAN1_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_RELEASE_KEYSCAN1_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_RELEASE_KEYSCAN1_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                                 /* @} */

/*! @name PORTD0 (number 2), ENCODER2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_RELEASE_ENCODER2_FGPIO FGPIOA             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_RELEASE_ENCODER2_GPIO GPIOA               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_RELEASE_ENCODER2_GPIO_PORT kGPIO_PORTD    /*!<@brief PORTA GPIO port: PORTA */
#define BOARD_INITPINS_RELEASE_ENCODER2_GPIO_PIN_MASK (1U << 24U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_RELEASE_ENCODER2_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_RELEASE_ENCODER2_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_RELEASE_ENCODER2_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                                 /* @} */

/*! @name PORTD1 (number 1), ENCODER1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_RELEASE_ENCODER1_FGPIO FGPIOA             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_RELEASE_ENCODER1_GPIO GPIOA               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_RELEASE_ENCODER1_GPIO_PORT kGPIO_PORTD    /*!<@brief PORTA GPIO port: PORTA */
#define BOARD_INITPINS_RELEASE_ENCODER1_GPIO_PIN_MASK (1U << 25U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_RELEASE_ENCODER1_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_RELEASE_ENCODER1_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_RELEASE_ENCODER1_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                                 /* @} */

/*! @name PORTD2 (number 46), GATEOUT1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_RELEASE_GATEOUT1_FGPIO FGPIOA             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_RELEASE_GATEOUT1_GPIO GPIOA               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_RELEASE_GATEOUT1_GPIO_PORT kGPIO_PORTD    /*!<@brief PORTA GPIO port: PORTA */
#define BOARD_INITPINS_RELEASE_GATEOUT1_GPIO_PIN_MASK (1U << 26U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_RELEASE_GATEOUT1_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_RELEASE_GATEOUT1_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_RELEASE_GATEOUT1_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                                 /* @} */

/*! @name PORTD3 (number 45), GATEOUT2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_RELEASE_GATEOUT2_FGPIO FGPIOA             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_RELEASE_GATEOUT2_GPIO GPIOA               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_RELEASE_GATEOUT2_GPIO_PORT kGPIO_PORTD    /*!<@brief PORTA GPIO port: PORTA */
#define BOARD_INITPINS_RELEASE_GATEOUT2_GPIO_PIN_MASK (1U << 27U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_RELEASE_GATEOUT2_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_RELEASE_GATEOUT2_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_RELEASE_GATEOUT2_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                                 /* @} */

/*! @name PORTD4 (number 44), GATEOUT3
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_RELEASE_GATEOUT3_FGPIO FGPIOA             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_RELEASE_GATEOUT3_GPIO GPIOA               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_RELEASE_GATEOUT3_GPIO_PORT kGPIO_PORTD    /*!<@brief PORTA GPIO port: PORTA */
#define BOARD_INITPINS_RELEASE_GATEOUT3_GPIO_PIN_MASK (1U << 28U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_RELEASE_GATEOUT3_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_RELEASE_GATEOUT3_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_RELEASE_GATEOUT3_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                                 /* @} */

/*! @name PORTD5 (number 24), P_KDAT
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_RELEASE_P_KDAT_FGPIO FGPIOA             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_RELEASE_P_KDAT_GPIO GPIOA               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_RELEASE_P_KDAT_GPIO_PORT kGPIO_PORTD    /*!<@brief PORTA GPIO port: PORTA */
#define BOARD_INITPINS_RELEASE_P_KDAT_GPIO_PIN_MASK (1U << 29U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_RELEASE_P_KDAT_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_RELEASE_P_KDAT_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_RELEASE_P_KDAT_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORTA0 (number 50), EXTSYNC
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_RELEASE_EXTSYNC_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_RELEASE_EXTSYNC_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_RELEASE_EXTSYNC_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                                /* @} */

/*! @name PORTB4 (number 19), KEYSCAN2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_RELEASE_KEYSCAN2_FGPIO FGPIOA             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_RELEASE_KEYSCAN2_GPIO GPIOA               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_RELEASE_KEYSCAN2_GPIO_PORT kGPIO_PORTB    /*!<@brief PORTA GPIO port: PORTA */
#define BOARD_INITPINS_RELEASE_KEYSCAN2_GPIO_PIN_MASK (1U << 12U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_RELEASE_KEYSCAN2_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_RELEASE_KEYSCAN2_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_RELEASE_KEYSCAN2_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                                 /* @} */

/*! @name PORTE7 (number 5), OFF_SWITCH
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_RELEASE_OFF_SWITCH_FGPIO FGPIOB             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_RELEASE_OFF_SWITCH_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_RELEASE_OFF_SWITCH_GPIO_PORT kGPIO_PORTE    /*!<@brief PORTB GPIO port: PORTB */
#define BOARD_INITPINS_RELEASE_OFF_SWITCH_GPIO_PIN_MASK (1U << 7U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_RELEASE_OFF_SWITCH_PORT PORTE               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_RELEASE_OFF_SWITCH_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_RELEASE_OFF_SWITCH_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                                   /* @} */

/*! @name PORTC7 (number 51), AUXIN
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_RELEASE_AUXIN_FGPIO FGPIOA             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_RELEASE_AUXIN_GPIO GPIOA               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_RELEASE_AUXIN_GPIO_PORT kGPIO_PORTC    /*!<@brief PORTA GPIO port: PORTA */
#define BOARD_INITPINS_RELEASE_AUXIN_GPIO_PIN_MASK (1U << 23U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_RELEASE_AUXIN_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_RELEASE_AUXIN_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_RELEASE_AUXIN_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORTA7 (number 37), AUXOUT
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_RELEASE_AUXOUT_FGPIO FGPIOA             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_RELEASE_AUXOUT_GPIO GPIOA               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_RELEASE_AUXOUT_GPIO_PORT kGPIO_PORTA    /*!<@brief PORTA GPIO port: PORTA */
#define BOARD_INITPINS_RELEASE_AUXOUT_GPIO_PIN_MASK (1U << 7U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_RELEASE_AUXOUT_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_RELEASE_AUXOUT_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_RELEASE_AUXOUT_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORTE2 (number 54), POWER_CTRL
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_RELEASE_POWER_CTRL_FGPIO FGPIOB             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_RELEASE_POWER_CTRL_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_RELEASE_POWER_CTRL_GPIO_PORT kGPIO_PORTE    /*!<@brief PORTB GPIO port: PORTB */
#define BOARD_INITPINS_RELEASE_POWER_CTRL_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_RELEASE_POWER_CTRL_PORT PORTE               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_RELEASE_POWER_CTRL_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_RELEASE_POWER_CTRL_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                                   /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins_Release(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
